version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  
  #init:
  #  image: init
  #  build: 
  #    context: ./init
  #  depends_on:
  #    - db

  kylin:
    image: apachekylin/apache-kylin-standalone:3.1.0
    ports:
      - "7070:7070"
      - "8088:8088"
      - "50070:50070"
      - "8032:8032"
      - "8042:8042"
      - "16010:16010"
    depends_on:
      - db
    volumes:
      - ./kylin.properties:/home/admin/apache-kylin-3.1.0-bin-hbase1x/conf/kylin.properties
      - ./postgresql-42.2.18.jar:/home/admin/apache-kylin-3.1.0-bin-hbase1x/ext/postgresql-42.2.18.jar
      - ./postgresql-42.2.18.jar:/home/admin/apache-kylin-3.1.0-bin-hbase1x/lib/postgresql-42.2.18.jar